### ISSUE TITLE
Make Manipulation more direct

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#10]
I suggest to use two modes for entering a data hunch: 

One action via direct manipulation: changing the value of a bar. 
All other actions via right-click on the bar in a context menu. 

When directly manipulating, I want to drag the upper edge of the bar. As soon as I start dragging, I get a sketchy bar that I drag.

**Comment by haihan-lin** [comment]
So how to get a range output from manipulation? We changed the original dragging the bar to a layer for manipulation because we want to get ranged output

**Comment by gotdairyya** [comment]
what if you drag like it's a point manipulation and then on hover there is a plus sign that lets you drag again for range?

**Comment by haihan-lin** [comment]
ok we can try that ( technically should be fine to achieve). might wait till Alex get back on this before I start

**Comment by alexsb** [comment]
Range and drag should be two different things. For range what we have right
now is probably fine.

**Comment by haihan-lin** [comment]
updated range, now use sketchy bar for range dragging. moved the input form below

issue: sketchy seems to not work very well, might need to implement a timer for it.

**Comment by haihan-lin** [comment]
haven't implemented rescaling chart yet. but bar dragging and range both have sketchy bar now.

**Comment by alexsb** [comment]
Let's not do rescaling for now.
