### ISSUE TITLE
Alternatives for Ranges

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#11]
I don't love our range encoding right now. Here are three alternative ideas: 

![IMG_D66D881A975B-1](https://user-images.githubusercontent.com/2039375/157102472-7083a01e-c408-478e-aeb8-f3eab43d4913.jpeg)

Maybe the second option is the easiest? 

Here's a simple design: 
![IMG_5B443B7A2A2D-1](https://user-images.githubusercontent.com/2039375/157102750-1bbd5b58-77a8-4f4d-b58b-b985bde6412d.jpeg)

Notice that the line tapers off as it radiates out from the center.

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/158646564-f6ad2bf9-0bf7-4bdd-89dc-7eb896420d89.png)

**Comment by haihan-lin** [comment]
@alexsb it looks good when there are no other single value hunches parallel.

**Comment by alexsb** [comment]
Yea, if there are multiple ones you'd have to put them at different vertical positions. But no need to do this now.

**Comment by alexsb** [comment]
Last point, before we can close this: this style should also be used as it's being created.

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/159541595-68d8446b-1a87-4bcc-b3dc-8c98445d26e8.png)
