### ISSUE TITLE
Weird issue with added bar disappearing when highlighting a sketch

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#13]
The bar "X" doesn't show up when I show the sketch via hover in the table: 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/2039375/159458438-b174a1fe-61ce-4fb8-bf49-64de33d49449.png">

Also, why doesn't the sketch always show up?

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-22 at 3 35 59 PM](https://user-images.githubusercontent.com/14115944/159580413-e1f7e26e-79cc-4a35-a251-358883ca179c.png)
