### ISSUE TITLE
Add a short timeout for hover to avoid flickering

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#15]
An item should be no longer hovered not immediately, but after ~500ms (play with the number to see what feels right). This would avoid annoying flickers we have now mostly because of the hatching.

**Comment by haihan-lin** [comment]
is this referring to tooltip? or the highlight?

**Comment by alexsb** [comment]
Highlight, for a tooltip I usually rest my mouse cursor. But it you make the highlight more stable, the tool-tip will probably also more stable.

**Comment by alexsb** [comment]
I guess an alternative would be to have a picking layer behind the sketchy surfaces. Because it's mostly a problem because I'm moving in between the sketchy lines.

**Comment by alexsb** [comment]
To be extra clear, this is what I mean: 

https://user-images.githubusercontent.com/2039375/159672563-7dd110a5-7f62-497d-853b-f0d638c820a9.mov

**Comment by haihan-lin** [comment]
added another transparent layer on top. fixed.

**Comment by alexsb** [comment]
Highlight
