### ISSUE TITLE
Refactor Toolbar

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#17]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/2039375/159469015-121fffbe-3ffb-4f5c-bb5d-50d8408f1026.png">

Rename title: 
 * Data Hunch Demo -> Data Hunches
 * Remove "Select a Data Point" (or do we still need it?)
 * Add Annotation -> is this the global chart annotation? I'd move it to below the legend, and have it as a link as opposed to a button? Call it "Leave a comment" 
 * Inclusion -> Add new value
 * Model Input -> Transform data
 * Graphical Annotations -> Add sketch

The Select Data should be a drop-down box, like this: 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/2039375/159470452-72051a15-03b1-48e2-9926-10691b40e48f.png">

The Select Vol should also be a drop-down box, showing "Data Hunch Demos:" 
* For the demos we want to have a demo for each type we can externalize and visualize. 
* We might want to add an info-box explaining that data hunch externalization method.

Show Category should be a "separate button" and not be caps. 
Sign in button should not be caps, and "Signed in as" is probably not necessary if a user is signed in.

**Comment by haihan-lin** [comment]
> Sign in button should not be caps, and "Signed in as" is probably not necessary if a user is signed in.

Clicking that button allows user to switch account and log out.

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/159798214-1318904b-2c65-479b-9075-b355f2ae2617.png)

For info box, maybe a ? icon, that opens a dialog, and gives a detailed explanation?

**Comment by alexsb** [comment]
> Clicking that button allows user to switch account and log out.

I meant that just a user icon is sufficient. No need for text, like on google:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2039375/159966718-5e0dea5e-52e6-4d4d-b301-ad8ef319d263.png">

**Comment by alexsb** [comment]
> ![image](https://user-images.githubusercontent.com/14115944/159798214-1318904b-2c65-479b-9075-b355f2ae2617.png)
> 
> For info box, maybe a ? icon, that opens a dialog, and gives a detailed explanation?

That might be a bit subtle? I was thinking of that explanation always being visible for these select hunches?

**Comment by haihan-lin** [comment]
Ok maybe a tooltip?

**Comment by alexsb** [comment]
It definitely should be in the tool tip. Let's start there. And we can add it later to the visualization if we have time/resources.

**Comment by alexsb** [comment]
I was thinking just a DIV on top of the table with a "warning" appearance https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by haihan-lin** [comment]
so what you are thinking is: while someone select a method to record hunches, here is what happens:

All the regular stuff we have right now
plus: an alert at the bottom of the page that gives a description of what this method is about

**Comment by alexsb** [comment]
No. That would only appear for the demo volumes we prepare for each type

**Comment by alexsb** [comment]
Looks great so far; I'd add a bit more space between the title and the buttons, like on the left of the title: 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/2039375/160106664-e701024d-c790-4b5b-91ba-cc4439fc50eb.png">
