### ISSUE TITLE
Improve Layout

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#18]
Here are some suggestions: 

![IMG_6EA495737F95-1](https://user-images.githubusercontent.com/2039375/159473697-478ce4a8-cd9c-4bfb-b7b7-9d27b776bee7.jpeg)

* reduce whitepace on left edge of chart 
* Increast font size of labels 
* Left align main title 
* Make sub-title go as wide as the whole chart (not shown in my sketch)
* Color tags to the left of labels for legend; left-align text in legend. 
* Move legend up
* Annotations go full width under the chart 
* Add a bit more space between annotations and bar

**Comment by alexsb** [comment]
Looks great so far, some minor additions: 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/2039375/160107437-1b7a21e5-caab-42c7-8b88-33785ccbd1ad.png">

The text is a bit close to the right now; add 5-10 px padding. 

And the title is a bit far to the right? Should we left-align the chart and the title?

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-25 at 5 33 47 PM](https://user-images.githubusercontent.com/14115944/160214654-2a489805-78f1-4c61-bfbe-5ebf4adbc6ee.png)

is this better?

**Comment by alexsb** [comment]
Yea, though the chart itself is still too far to the right for my taste.
