### ISSUE TITLE
Add a welcome dialog pop-up. 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#21]
Text: 

> Welcome to the the demonstrator for the paper "Data Hunches: Incorporating Personal Knowledge into Visualizations". 
> 
> A data hunch is an analyst's knowledge about how and why the data is an imperfect and partial representation of the phenomena of interest.
> 
> In this demonstrator, we show some ideas how data hunches could be recorded and visualized, on top of but distinct from data visualizations. 
> 
> Browse through the different types of demonstration hunches we pre-recorded, or try recording some of your own by right-clicking a bar or using one of the buttons. 
> 
> To record a data hunch, use the "Log in as Guest" feature. 
> 
> Note that we do not track anything about visitors to this website!

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-23 at 12 54 34 PM](https://user-images.githubusercontent.com/14115944/159774855-47051e5c-4bdd-4df7-8255-11a3c5b40695.png)
