### ISSUE TITLE
Improve Tool Tips

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#22]
Tool Tips could be useful to make sure that ppl can easily understand a data hunch. Here are a few examples and redesign suggestions: 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2039375/159487129-357ea67f-9f08-432b-8e17-ef63d7d35069.png">

This tool tip could be: 

> Hunch: The category should be () Europe
> Comment: Turkey is historically part of Europe
> Author: Haihan 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/2039375/159487457-2e36a798-80d6-4300-a8f8-f29b13c00bb8.png">
This tool tip could be: 
> Hunch: The value should be ~2200
> Comment: This contains test values from the weekend. 
> Author: Alex

**Comment by alexsb** [comment]
Also, all other information we have about a hunch (e.g., confidence) should be in the tool bar.

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-23 at 3 56 26 PM](https://user-images.githubusercontent.com/14115944/159803125-fbf9b7a9-56d3-46c7-99c3-80e7eb41849c.png)
