### ISSUE TITLE
Directionality Data Hunches

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#23]
should be higher / lower

**Comment by alexsb** [comment]
Thinking about this a bit more, I think just a hand-drawn arrow pointing up or down would probably do the trick.

**Comment by haihan-lin** [comment]
Do we want to include this as part of the existing input? maybe data space? having an option that instead of a value, the user can provide a direction? Because the menu is growing a bit too long at the moment.

**Comment by alexsb** [comment]
These can get big: 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/2039375/159529959-e8439d13-344e-4432-a4c3-f070468da6ea.png">

I think being explicit is more important than being space efficient. 

I'd consider even two separate options "Value should be higher" and "Value should be lower".

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/159807459-bb59f248-aaee-4779-a6dd-9d64dbe2535d.png)

I have the input ready

With indicators, arrows should be the most obvious option, however it wouldn't be very scalable. Do we want to just do maybe 3-4 arrows?

**Comment by alexsb** [comment]
Since this is a binary issue, we could also "upvote" hunches? I think that would generally be a good idea? Thoughts?

Generally I wouldn't worry about scalability for this. 

Just in case: not red :)

**Comment by haihan-lin** [comment]
upvote/downvote can be done through a left click on hunches in chart, but to show it, maybe we do it in the table?

**Comment by alexsb** [comment]
Or we add icons? Thumbs up icons?

 https://fontawesome.com/v5/icons/thumbs-up?s=solid

I'd really prefer it to be visible outside the table.

**Comment by haihan-lin** [comment]
it would be rather not easy to place all thumbs up/thumbs down directly visible in the visualization.

A work around would be showing the thumbs up and down in the tooltip upon hovering

**Comment by alexsb** [comment]
It definitely should be in the tool tip. Let's start there. And we can add it later to the visualization if we have time/resources.

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-24 at 4 21 34 PM](https://user-images.githubusercontent.com/14115944/160019831-5c5dc188-10f9-4366-bb52-63ab4ded12f4.png)

**Comment by alexsb** [comment]
Looks great, a few comments: 

* The arrows could be bigger (maybe by 1/3). I realize that hampers scalability ab it, but it would look better for individual hunches. 
* The context menu has a period . for these menu items, but the other menu items don't. Remove the period.

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-25 at 5 39 57 PM](https://user-images.githubusercontent.com/14115944/160214963-856b9d53-8ae2-4ea8-a3a9-df53e85fea0a.png)
