### ISSUE TITLE
Re-think categorical hunches

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#24]
Here are two alternative designs: 

![IMG_1ECF92D44CD4-1](https://user-images.githubusercontent.com/2039375/159551292-e6bfcca8-07c7-47ef-ae09-59240d688f45.jpeg)

A label with the legend color, either below or next to the bar (next is probably easier to consistently implement). 

A rough sketchy fill color, with a thin pen. 

Then I figured, we could also try a thick fill with a pen, almost if a child had colored it sloppily. This would also make eat easy to show to diverging hunches: 

![IMG_49490D756068-1](https://user-images.githubusercontent.com/2039375/159551867-effa6ce8-7680-4e69-96c2-21e1082e39ab.jpeg)

Thoughts?

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-28 at 1 30 14 PM](https://user-images.githubusercontent.com/14115944/160472512-df01f159-492b-4aa3-a882-f71e2e3ed6e6.png)
