### ISSUE TITLE
Issues with Pop-Up Menu

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#27]
There are sometimes clipping issues: 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/2039375/160109858-1460fba2-4fcc-4ea4-8f74-0ef96ce11dce.png">

And here it suddenly appears not as a floating menu, but as part of the layout: 

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2039375/160109969-08771df1-dfe1-441c-8154-79a4bc790f2b.png">

**Comment by alexsb** [comment]
I see these clipping issues also for annotation menus and for the context menu. It's actually making it impossible to do quite a few things. Are you doing all of these by hand? Could you use a reasonable context-menu implementation / floating menu implementation instead?

**Comment by alexsb** [comment]
Here's a recommendation by @puehringer :

Context-menus need to behave the same way as modals, popovers, ..., i.e. they need to be above everything else. One way is by hacking around with z-index, but the generally accepted solution is to mount a new node on the very bottom of body, and render everything in there with absolute positioning.
That way, you won't run into these clipping issues. Popper and nearly all other libraries solve it like this. In React, it is useful to use createPortal to avoid the complex page-flow that comes with that.

**Comment by haihan-lin** [comment]
absolute positioning doesn't work when you have combination of svg and divs. divs on top of divs are easy, but divs cannot be on top of svg, you need foreignObject for that.

**Comment by haihan-lin** [comment]
or at least I remember it is like so the last time I did something similar

**Comment by haihan-lin** [comment]
maybe it is just z-index itself doesn't work with SVG. looks like absolute positioning does. I can change it to absolute positioning since part of code use it already
