### ISSUE TITLE
"Star"ratings should be rendered as stars, not as "4 *" 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#28]
So we always want to see 5 stars, but in case of a 3-star rating, three of them should be saturated/blue, and two should be light-gray.

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-25 at 6 10 36 PM](https://user-images.githubusercontent.com/14115944/160216396-350be122-6f35-48d1-b3a5-6393ec5d11cc.png)

**Comment by alexsb** [comment]
I was expecting this to be hand-drawn stars, but these are fine too.
