### ISSUE TITLE
Improve off-scale data hunches

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#5]
I don't like the current off-scale implementation of data hunches. They don't look good and aren't all that effective. 

<img width="161" alt="image" src="https://user-images.githubusercontent.com/2039375/157098031-c2116956-4921-46e1-a776-f86d8f1b0a7d.png">

Here's a different idea. 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/2039375/157098127-7a10269c-35dd-45a8-9e97-e18da1d6a81f.png">

Use a sketchy arrow and point to a label that corresponds to the new data value. The brush can be of constant shape or height, so could be a glyph instead of a customly rendered arrow. 

The above design shows two variations for more than one hunch; one with two arrows, one with one arrow, and multiple numbers shown in a list. Multiple numbers would make it easier to implement and probably more scalable. 

Use a hand-written font for this, and for all other occurrences where we print text from a data hunch. For example https://www.1001fonts.com/gooddog-plain-font.html

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/158696584-b834e5fb-740e-4c7c-8160-cdd62fdee582.png)

**Comment by alexsb** [comment]
I think the arrows should point sideways instead of downwards. And the text should be next to it, not under? The way this is right now it looks like 20, 19, and 40 are at these positions where the arrows end.

**Comment by haihan-lin** [comment]
![WeChat348c9d5b022f50f77a6b09a43733e079](https://user-images.githubusercontent.com/14115944/159187867-846d7112-9121-4ce3-9191-1a87a71b1ec1.png)

**Comment by alexsb** [comment]
Yes, this is good. Let's try to give examples that are in sequential order, but no need to change anything with the implementation.
