### ISSUE TITLE
Fix selection

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#6]
* Selection from hunch to table doesn't work. 
* No selection feedback exists for sketchy bars. Make them "bolder" or change color from a user color to the bright orange?
* Multiple selection from the table should work. It's pretty irritating that when I click that an item gets deselected (as opposed to hover)
* I don't like the switching from a "dash" to a "bar" for the cases with multiple dashes. let's just stick with dashes?

**Comment by haihan-lin** [comment]
> I don't like the switching from a "dash" to a "bar" for the cases with multiple dashes. let's just stick with dashes?

Do you mean all value based DH use a bar for indicator and goes full bar on hover?

**Comment by haihan-lin** [comment]
will fix #2 with this, depending on how we want it to look

**Comment by alexsb** [comment]
I mean that if we use a tick/dash for a value based DH (which we do if we have more than a few of them for a bar) then we stick with the tick/dash.

**Comment by haihan-lin** [comment]
What would be the difference in chart behavior between "on hover" from the table/chart and table selection?

**Comment by haihan-lin** [comment]
![Screen Shot 2022-03-13 at 3 22 13 PM](https://user-images.githubusercontent.com/14115944/158079791-893e8f4c-77d3-42fc-bee2-726a4dd92a84.png)

Added multi selection, select DH to reflect to table
