### ISSUE TITLE
Qualitative Comments 

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#9]
We should do qualitative comments like hand-written annotations. For example, if there is a comment on the whole chart, we should just show that comment below the title. To do that, we should move the title to the bottom, so that we have space. That would make qualitative hunches more immediate.

As we flip the chart over sideways, we will also have space to write out comments about individual bars. If things get to long, we can always use an ellipsis and show the rest on hover.

**Comment by haihan-lin** [comment]
0.0.18 resolves this

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/157726518-f7294cdd-b721-44b8-9b79-8ebdc5721e6d.png)
